# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX package structure
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official

# Maven Publishing Metadata
GROUP=io.github.krishnapensalwar
POM_ARTIFACT_ID=devkit
VERSION_NAME=1.0.1-SNAPSHOT

POM_NAME=DevKit
POM_DESCRIPTION=Android Developer Toolkit for networking, logging and UI debugging.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/KrishnaPensalwar/DevToolSDK

POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/KrishnaPensalwar/DevToolSDK
POM_SCM_CONNECTION=scm:git:git://github.com/KrishnaPensalwar/DevToolSDK.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/KrishnaPensalwar/DevToolSDK.git

POM_DEVELOPER_ID=KrishnaPensalwar
POM_DEVELOPER_NAME=Krishna Pensalwar
POM_DEVELOPER_EMAIL=krishnapensalwar3@gmail.com